name: Fetch POE Store
on: 
   schedule:
    - cron:  '0 0 * * *'
   workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: cd ..
      - run: npm install
      - run: ls
      - run: node index.js
      - run: echo "test"
