name: GitHub Actions Demo
on: 
   schedule:
    - cron:  '0 0 * * *'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - run: node index.js
      - run: echo "test"
